CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "citext";

CREATE TYPE user_role AS ENUM ('USER','ADMIN','SUPER_ADMIN','RISK_MANAGER','SUPPORT_AGENT','PAYMENT_AGENT','TRADER');
CREATE TYPE kyc_status AS ENUM ('NOT_STARTED','PENDING','VERIFIED','REJECTED','REQUIRES_INFO');
CREATE TYPE kyc_level AS ENUM ('BASIC','INTERMEDIATE','ADVANCED');
CREATE TYPE currency_type AS ENUM ('USD','EUR','GBP','NGN','KES','ZAR');

CREATE TABLE users (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),email CITEXT UNIQUE NOT NULL,username VARCHAR(30) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,phone VARCHAR(20),role user_role NOT NULL DEFAULT 'USER',is_email_verified BOOLEAN NOT NULL DEFAULT FALSE,is_phone_verified BOOLEAN NOT NULL DEFAULT FALSE,is_active BOOLEAN NOT NULL DEFAULT TRUE,is_suspended BOOLEAN NOT NULL DEFAULT FALSE,suspension_reason TEXT,mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,mfa_secret VARCHAR(64),mfa_backup_codes TEXT[],kyc_status kyc_status NOT NULL DEFAULT 'NOT_STARTED',kyc_level kyc_level NOT NULL DEFAULT 'BASIC',last_login_at TIMESTAMPTZ,last_login_ip INET,login_attempts INTEGER NOT NULL DEFAULT 0,locked_until TIMESTAMPTZ,preferred_currency currency_type NOT NULL DEFAULT 'USD',preferred_language VARCHAR(10) NOT NULL DEFAULT 'en',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE user_profiles (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,first_name VARCHAR(100) NOT NULL,last_name VARCHAR(100) NOT NULL,date_of_birth DATE NOT NULL,country VARCHAR(2) NOT NULL,state VARCHAR(100),city VARCHAR(100),address_line1 VARCHAR(255),postal_code VARCHAR(20),avatar_url TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE sessions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash VARCHAR(255) UNIQUE NOT NULL,refresh_token_hash VARCHAR(255),device_type VARCHAR(50),ip_address INET NOT NULL,user_agent TEXT,is_current BOOLEAN NOT NULL DEFAULT FALSE,last_active_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),expires_at TIMESTAMPTZ NOT NULL,revoked_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE email_verifications (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,token VARCHAR(255) UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,verified_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE password_resets (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,token VARCHAR(255) UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE mfa_challenges (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,token VARCHAR(255) UNIQUE NOT NULL,is_verified BOOLEAN NOT NULL DEFAULT FALSE,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_kyc_status ON users(kyc_status);
CREATE INDEX idx_sessions_user_id ON sessions(user_id);

CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$ LANGUAGE plpgsql;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();