CREATE TYPE document_status AS ENUM ('PENDING','APPROVED','REJECTED','EXPIRED');
CREATE TYPE promotion_type AS ENUM ('WELCOME','DEPOSIT_BONUS','FREE_BET','CASHBACK','ODDS_BOOST','VIP','LOYALTY');
CREATE TYPE bonus_status AS ENUM ('ACTIVE','USED','EXPIRED','FORFEITED');
CREATE TYPE limit_type AS ENUM ('DEPOSIT_DAILY','DEPOSIT_WEEKLY','DEPOSIT_MONTHLY','LOSS_DAILY','LOSS_WEEKLY','LOSS_MONTHLY','SESSION_MINUTES');
CREATE TYPE exclusion_type AS ENUM ('COOLING_OFF','SELF_EXCLUSION');
CREATE TYPE notification_type AS ENUM ('BET_PLACED','BET_SETTLED','ODDS_CHANGED','DEPOSIT','WITHDRAWAL','PROMOTION','KYC_UPDATE','SECURITY_ALERT','SYSTEM','RESPONSIBLE_GAMBLING');

CREATE TABLE kyc_records (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id),level kyc_level NOT NULL DEFAULT 'BASIC',status kyc_status NOT NULL DEFAULT 'PENDING',rejection_reason TEXT,reviewer_id UUID REFERENCES users(id),reviewed_at TIMESTAMPTZ,notes TEXT,metadata JSONB DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE kyc_documents (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),kyc_record_id UUID NOT NULL REFERENCES kyc_records(id) ON DELETE CASCADE,document_type VARCHAR(50) NOT NULL,document_url TEXT NOT NULL,status document_status NOT NULL DEFAULT 'PENDING',verified_by VARCHAR(50),rejection_reason TEXT,expiry_date DATE,metadata JSONB DEFAULT '{}',uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),verified_at TIMESTAMPTZ);
CREATE TABLE aml_screenings (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id),screening_type VARCHAR(50) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'PENDING',is_match BOOLEAN NOT NULL DEFAULT FALSE,match_details JSONB DEFAULT '{}',screened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE risk_scores (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id),score INTEGER NOT NULL DEFAULT 0 CHECK(score>=0 AND score<=100),factors JSONB DEFAULT '{}',calculated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

CREATE TABLE promotions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),name VARCHAR(255) NOT NULL,description TEXT,type promotion_type NOT NULL,code VARCHAR(30) UNIQUE,min_odds DECIMAL(10,3),min_stake DECIMAL(12,2),max_bonus DECIMAL(12,2) NOT NULL,bonus_percent DECIMAL(5,2),wagering_requirement INTEGER NOT NULL DEFAULT 1,wagering_multiplier DECIMAL(5,2) NOT NULL DEFAULT 1.0,is_active BOOLEAN NOT NULL DEFAULT TRUE,is_public BOOLEAN NOT NULL DEFAULT TRUE,max_usage INTEGER,usage_count INTEGER NOT NULL DEFAULT 0,min_kyc_level kyc_level NOT NULL DEFAULT 'BASIC',eligible_countries TEXT[],terms_and_conditions TEXT,starts_at TIMESTAMPTZ NOT NULL,expires_at TIMESTAMPTZ NOT NULL,created_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE bonuses (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id),promotion_id UUID NOT NULL REFERENCES promotions(id),amount DECIMAL(12,2) NOT NULL,status bonus_status NOT NULL DEFAULT 'ACTIVE',wagering_requirement DECIMAL(12,2) NOT NULL,wagering_completed DECIMAL(12,2) NOT NULL DEFAULT 0.00,expires_at TIMESTAMPTZ NOT NULL,earned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),used_at TIMESTAMPTZ,forfeited_at TIMESTAMPTZ,metadata JSONB DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE vip_tiers (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),name VARCHAR(50) NOT NULL UNIQUE,level INTEGER NOT NULL UNIQUE,min_points INTEGER NOT NULL,benefits JSONB DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE loyalty_points (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id),points INTEGER NOT NULL DEFAULT 0,tier_id UUID REFERENCES vip_tiers(id),lifetime_points INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

CREATE TABLE responsible_gambling_limits (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id),limit_type limit_type NOT NULL,limit_value DECIMAL(12,2) NOT NULL,current_value DECIMAL(12,2) NOT NULL DEFAULT 0.00,period_start TIMESTAMPTZ NOT NULL DEFAULT NOW(),period_end TIMESTAMPTZ NOT NULL,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,limit_type,period_start));
CREATE TABLE self_exclusions (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id),type exclusion_type NOT NULL,starts_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),ends_at TIMESTAMPTZ NOT NULL,reason TEXT,is_active BOOLEAN NOT NULL DEFAULT TRUE,revoked_at TIMESTAMPTZ,revoked_by UUID REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE reality_checks (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id),session_start TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_reminder_at TIMESTAMPTZ,check_interval_minutes INTEGER NOT NULL DEFAULT 60,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

CREATE TABLE notifications (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL REFERENCES users(id),type notification_type NOT NULL,title VARCHAR(255) NOT NULL,message TEXT NOT NULL,is_read BOOLEAN NOT NULL DEFAULT FALSE,action_url TEXT,metadata JSONB DEFAULT '{}',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE notification_preferences (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),user_id UUID NOT NULL UNIQUE REFERENCES users(id),push_enabled BOOLEAN NOT NULL DEFAULT TRUE,email_enabled BOOLEAN NOT NULL DEFAULT TRUE,sms_enabled BOOLEAN NOT NULL DEFAULT FALSE,odds_change_enabled BOOLEAN NOT NULL DEFAULT TRUE,promo_enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

CREATE INDEX idx_kyc_records_user_id ON kyc_records(user_id);
CREATE INDEX idx_promotions_code ON promotions(code);
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_user_read ON notifications(user_id, is_read);