'use client';
import React from'react';import{useBetSlipStore}from'@/lib/stores/betSlipStore';import{Star}from'lucide-react';

interface EventCardProps{event:any}

export function EventCard({event}:EventCardProps){
  const{addItem,items}=useBetSlipStore();
  const isSelected=(id:string)=>items.some(i=>i.selectionId===id);
  const handleSelect=(sel:any,marketId:string)=>{addItem({eventId:event.id,eventName:`${event.homeTeam} vs ${event.awayTeam}`,marketId,marketName:event.markets[0].name,selectionId:sel.id,selectionName:sel.name,odds:sel.odds,homeTeam:event.homeTeam,awayTeam:event.awayTeam,startTime:event.startTime,isLive:event.isLive})};
  return <div className='bg-surface-light border border-surface-border rounded-bet overflow-hidden hover:border-primary/30 transition-all'><div className='px-4 py-3 border-b border-surface-border flex items-center justify-between'><div className='flex items-center gap-2'><span className='text-lg'>{event.sport?.icon||'⚽'}</span><div><div className='text-xs text-text-muted'>{event.competition?.name}</div></div></div><div className='flex items-center gap-2'>{event.isLive&&<span className='flex items-center gap-1 text-xs text-error font-semibold'><span className='w-2 h-2 bg-error rounded-full live-pulse'/>{event.clock||'LIVE'}</span>}<button className='text-text-muted hover:text-primary'><Star size={14}/></button></div></div><div className='px-4 py-4'><div className='flex items-center justify-between'><div><div className='text-base font-semibold'>{event.homeTeam}</div><div className='text-base font-semibold mt-1'>{event.awayTeam}</div></div>{event.isLive?<div className='text-right'><div className='text-xl font-bold'>{event.homeScore}</div><div className='text-xl font-bold mt-1'>{event.awayScore}</div></div>:<div className='text-xs text-text-muted'>{new Date(event.startTime).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div>}</div></div>{event.markets?.slice(0,2).map((m:any)=><div key={m.id} className='px-4 py-2 border-t border-surface-border'><div className='text-xs text-text-muted mb-2'>{m.name}</div><div className='grid grid-cols-3 gap-2'>{m.selections?.map((s:any)=><button key={s.id} onClick={()=>handleSelect(s,m.id)} disabled={s.status!=='OPEN'} className={`py-2 rounded-bet text-center text-xs font-medium transition-all ${isSelected(s.id)?'bg-primary/20 border border-primary text-primary font-bold':s.status==='OPEN'?'bg-surface border border-surface-border-light hover:border-primary/50 hover:bg-surface-lighter':'bg-surface/50 text-text-muted line-through'}`}><div className='text-[10px] text-text-muted'>{s.name}</div><div className='text-sm font-bold'>{s.odds.toFixed(2)}</div></button>)}</div></div>)}</div>;
}